#!/bin/sh

domain=$1
maildom="mail.$domain"
firstuse="true"

replace() { \
sed "s/<domain>/$domain/g;s/<maildom>/$maildom/g" $1
}

success() { \
    echo "\033[1;32m========================================================================"
    echo "$@"
    echo "========================================================================\033[0m"
}

failure() { \
    echo "\033[1;31m========================================================================"
    echo "$@"
    echo "========================================================================\033[0m"
}

#
# register domain
#

[ -f /etc/mail/maindom ] && firstuse="false"

[ $firstuse = "true" ] &&
echo "$domain" > /etc/mail/maindom

grep -q "$domain" /etc/mail/domains > /dev/null ||
echo "$domain" >> /etc/mail/domains

#
# install required software
#

pkg_add -u &&
pkg_add -I opensmtpd-extras opensmtpd-filter-rspamd dovecot \
    dovecot-pigeonhole rspamd-3.0 redis sieve tor &&

success "Installed required software"

#
# certs
#

[ $firstuse = "true" ] &&

replace files/acme-client.conf >> /etc/acme-client.conf &&

replace files/httpd.conf >> /etc/httpd.conf &&

rcctl enable httpd &&
rcctl restart httpd &&

acme-client -v $maildom &&

replace files/daily.local >> /etc/daily.local &&

success "Created and signed tls certificates (letencrypt)"

#
# vmail user & authentication
#

[ $firstuse = "true" ] &&

touch /etc/mail/credentials &&
chmod 0440 /etc/mail/credentials &&
chown _smtpd:_dovecot /etc/mail/credentials &&
useradd -c "Virtual Mail Account" -d /var/vmail -s /sbin/nologin \
    -u 2000 -g =uid -L staff vmail &&
mkdir -p /var/vmail &&
chown vmail:vmail /var/vmail &&

replace files/virtuals >> /etc/mail/virtuals &&

success "Created vmail user & authentication file"

#
# smtpd
#

[ $firstuse = "true" ] &&

replace files/smtpd.conf > /etc/mail/smtpd.conf &&

cp files/madduser /usr/local/bin/ &&
cp files/mdeluser /usr/local/bin/ &&

success "Configured OpenSMTPD"

#
# dovecot
#

[ $firstuse = "true" ] &&

echo "dovecot:\\
        :openfiles-cur=1024:\\
        :openfiles-max=2048:\\
        :tc=daemon:
" >> /etc/login.conf &&

replace files/local.conf > /etc/dovecot/local.conf &&

sed "s/^ssl_cert/#ssl_cert/;s/^ssl_key/#ssl_key/" \
	/etc/dovecot/conf.d/10-ssl.conf > tempfile &&
mv tempfile /etc/dovecot/conf.d/10-ssl.conf &&

# setup training rspamd from email moving in and out of the Junk folder

mkdir -p /usr/local/lib/dovecot/sieve &&
cp files/report-ham.sieve /usr/local/lib/dovecot/sieve &&
cp files/report-spam.sieve /usr/local/lib/dovecot/sieve &&
sievec /usr/local/lib/dovecot/sieve/report-ham.sieve &&
sievec /usr/local/lib/dovecot/sieve/report-spam.sieve &&

cp files/sa-learn-ham.sh /usr/local/lib/dovecot/sieve/ &&
cp files/sa-learn-spam.sh /usr/local/lib/dovecot/sieve/ &&
chmod 0755 /usr/local/lib/dovecot/sieve/sa-learn-ham.sh &&
chmod 0755 /usr/local/lib/dovecot/sieve/sa-learn-spam.sh &&

rcctl enable dovecot &&
rcctl start dovecot &&

success "Configured Dovecot"

#
# rspamd
#

[ $firstuse = "true" ] &&

mkdir -p /etc/mail/dkim &&
openssl genrsa -out /etc/mail/dkim/$domain.key 1024 &&
openssl rsa -in /etc/mail/dkim/$domain.key \
	    -pubout -out /etc/mail/dkim/public.key &&
chmod 0440 /etc/mail/dkim/$domain.key &&
chown root:_rspamd /etc/mail/dkim/$domain.key &&

replace files/dkim_signing.conf > /etc/rspamd/local.d/dkim_signing.conf &&

rcctl enable redis rspamd &&
rcctl start redis rspamd &&
rcctl restart smtpd &&

success "Configured rspamd"

#
# dns
#

[ $firstuse = "true" ] &&

pub_key=$(grep -v -e "---" /etc/mail/dkim/public.key | tr -d '\n' ) &&
mkdir -p /etc/mail/dns/$domain &&
echo "mail._domainkey.$domain. IN TXT \"v=DKIM1;k=rsa;p=$pub_key\"" > /etc/mail/dns/$domain/dkim &&
echo "$domain. IN TXT \"v=spf1 mx -all\"" > /etc/mail/dns/$domain/spf &&
echo "_dmarc.$domain. IN TXT
\"v=DMARC1;p=quarantine;pct=100;rua=mailto:postmaster@$domain\"" > /etc/mail/dns/$domain/dmarc &&
echo "$domain. IN MX 0 $maildom." > /etc/mail/dns/$domain/mx &&
success "Wrote relevant dns records in /etc/mail/dns/$domain/"

[ $firstuse = "false" ] &&

echo "$domain. IN MX 0 $maildom." > /etc/mail/dns/$domain/mx &&
success "Wrote relevant dns records in /etc/mail/dns/$domain/"

# TODO: does .forward work with virtual users?

[ $firstuse = "true" ] &&

success \
"The creation of an admin account is required for this setup! Email to
it can be forwarded to an email address written in:
/var/vmail/$domain/admin/.forward
Please choose a password for the \"admin\" user." &&

madduser $domain admin &&
rcctl restart smtpd

success "Done!"
