#!/bin/sh

if [ $# != 2 ]; then
    echo "Error: Invalid number of arguments"
    echo "Usage: madduser DOMAIN USERNAME"
    return 1
fi

domain=$1
user=$2

if [ -z "$(grep "$domain" /etc/mail/domains 2> /dev/null)" ]; then
    echo "Error: Invalid domain"
    echo "Info: It should be one of the following:"
    cat /etc/mail/domains
    return 1
fi

if [ -n "$(grep "^$user@$domain" /etc/mail/credentials 2> /dev/null)" ]; then
    echo "Error: User already exists in /etc/mail/credentials"
    return 1
fi

if [ -n "$(grep "^$user@$domain" /etc/mail/virtuals 2> /dev/null)" ]; then
    echo "Error: User already exists in /etc/mail/virtuals"
    return 1
fi

echo -n "Password: "
stty -echo
read password
stty echo
echo

record="$(smtpctl encrypt "$password")"
record="$user@$domain:$record:vmail:2000:2000:/var/vmail/$domain/$user::userdb_mail=maildir:/var/vmail/$domain/$user"
echo "$record" >> /etc/mail/credentials

echo "$user@$domain: vmail" >> /etc/mail/virtuals
