#!/bin/sh

[ $# != 2 ] &&
echo "Error: Invalid number of arguments" &&
echo "Usage: madduser DOMAIN USERNAME"

domain=$1
user=$2

grep "$domain" /etc/mail/domains > /dev/null ||
echo "Error: Invalid domain" &&
echo "Info: It should be one of the following:" &&
cat /etc/mail/domains &&
return 1

grep "^$user@$domain" /etc/mail/credentials > /dev/null ||
echo "Error: User already exists in /etc/mail/credentials" && return 1

grep "^$user@$domain" /etc/mail/virtuals > /dev/null ||
echo "Error: User already exists in /etc/mail/virtuals" && return 1

echo -n "Password: "
stty -echo
read password
stty echo

record="$(smtpctl encrypt "$password")"
record="$user@$domain:$record:vmail:2000:2000:/var/vmail/$domain/$user::userdb_mail=maildir:/var/vmail/$domain/$user"
echo "$record" >> /etc/mail/credentials

echo "$user@$domain: vmail" >> /etc/mail/virtuals
