#!/bin/sh

if [ $# != 1 ]; then
    echo "Error: Invalid number of arguments"
    echo "Usage: mdeluser username@domain.tld"
    return 1
fi

user="$(echo $1 | cut -d '@' -f 1)"
domain="$(echo $1 | cut -d '@' -f 2)"

if [ -z "$(grep "$domain" /etc/mail/domains 2> /dev/null)" ]; then
    echo "Error: Invalid domain"
    echo "Info: It should be one of the following:"
    cat /etc/mail/domains
    return 1
fi

if [ -z "$(grep "^$user@$domain" /etc/mail/credentials 2> /dev/null)" ]; then
    echo "Error: User doesn't exist in /etc/mail/credentials"
    return 1
fi

if [ -z "$(grep "^$user@$domain" /etc/mail/virtuals 2> /dev/null)" ]; then
    echo "Error: User doesn't exist in /etc/mail/virtuals"
    return 1
fi

echo -n "Delete user \"$user\"? (y/n): " &&
read responce &&
[ $responce = "y" ] &&
sed "/^$user@$domain/d" /etc/mail/credentials > temp-cred-file &&
mv temp-cred-file /etc/mail/credentials &&
sed "/^$user@$domain/d" /etc/mail/virtuals > temp-virt-file &&
mv temp-virt-file /etc/mail/virtuals

echo -n "Delete all mail belonging to user \"$user\"? (y/n): " &&
read responce &&
[ $responce = "y" ] &&
rm -rf /var/vmail/$domain/$user ||
return 0

rcctl restart smtpd
rcctl restart dovecot
