#!/bin/sh

if [ $# != 1 ]; then
    echo "Error: Invalid number of arguments"
    echo "Usage: mpasswd username@domain.tld"
    return 1
fi

user="$(echo $1 | cut -d '@' -f 1)"
domain="$(echo $1 | cut -d '@' -f 2)"

if [ -z "$(grep "$domain" /etc/mail/domains 2> /dev/null)" ]; then
    echo "Error: Invalid domain"
    echo "Info: It should be one of the following:"
    cat /etc/mail/domains
    return 1
fi

if [ -z "$(grep "^$user@$domain" /etc/mail/credentials 2> /dev/null)" ]; then
    echo "Error: User doesn't exist in /etc/mail/credentials"
    return 1
fi

if [ -z "$(grep "^$user@$domain" /etc/mail/virtuals 2> /dev/null)" ]; then
    echo "Error: User doesn't exist in /etc/mail/virtuals"
    return 1
fi

echo "Please enter a password."
password=$(encrypt -p)

record="$user@$domain:$password:vmail:2000:2000:/var/vmail/$domain/$user::userdb_mail=maildir:/var/vmail/$domain/$user"

sed "s#^$user@$domain.*#$record#g" /etc/mail/credentials > temp-cred-file
mv temp-cred-file /etc/mail/credentials

rcctl restart smtpd
rcctl restart dovecot
